### ISSUE TITLE
Graceful unmount

### ISSUE THREAD

**Issue by overheadhunter** [cryptomator/fuse-nio-adapter#29]
At the moment the filesystem gets closed even if unmount failed:

https://github.com/cryptomator/fuse-nio-adapter/blob/cb7d3df6d288ca0101cc1d9d35eaf84b8fc46d46/src/main/java/org/cryptomator/frontend/fuse/mount/AbstractMount.java#L31-L41

This is incorrect and needs to be improved.

**Comment by overheadhunter** [comment]
Graceful unmount works fine, however forced unmount doesn't:

```
org.cryptomator.frontend.fuse.mount.CommandFailedException: Command failed with exit code 1. Expected 0. Stderr: umount: only root can use "--force" option
        at org.cryptomator.frontend.fuse.mount.ProcessUtil.assertExitValue(ProcessUtil.java:26)
        at org.cryptomator.frontend.fuse.mount.AbstractMount.unmountForced(AbstractMount.java:62)
        at org.cryptomator.ui.model.FuseVolume.unmountForced(FuseVolume.java:117)
```
