### ISSUE TITLE
utimens doesn't work on symlinks

### ISSUE THREAD

**Issue by overheadhunter** [cryptomator/fuse-nio-adapter#32]
There is a [`NOFOLLOW_LINKS`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/nio/file/LinkOption.html#NOFOLLOW_LINKS) missing in [`getFileAttributeView()`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/nio/file/Files.html#getFileAttributeView(java.nio.file.Path,java.lang.Class,java.nio.file.LinkOption...)):

https://github.com/cryptomator/fuse-nio-adapter/blob/f2a071714383fb51129c50cfdbc10973e047f2e4/src/main/java/org/cryptomator/frontend/fuse/ReadWriteFileHandler.java#L137-L140

This leads to errors when attempting to set the file times of symlinks (as described in cryptomator/cryptomator#853).

Before blindly fixing this, we need to find out how [`AT_SYMLINK_NOFOLLOW`](https://linux.die.net/man/2/utimensat) is to be handled correctly in FUSE.

**Comment by overheadhunter** [comment]
Test case: `touch -ht 1546300800.00 link`

**Comment by overheadhunter** [comment]
Adding `NOFOLLOW_LINKS` doesn't work due to a [JDK bug](https://stackoverflow.com/a/20714826/4014509) in NIO leading to

```
java.nio.file.FileSystemException: /path/to/symlink: Too many levels of symbolic links or unable to access attributes of symbolic link
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:96)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.setTimes(UnixFileAttributeViews.java:85)
```

I've reported this to Oracle in the hope that they will create a bug report on bugs.openjdk.java.net.

At the moment this issue is blocked by an upstream bug with no feasible workaround. I will update this issue as soon as there is any public progress.
