### ISSUE TITLE
open: java.io.IOException thrown when accessing a file

### ISSUE THREAD

**Issue by infeo** [cryptomator/fuse-nio-adapter#6]
## Basic Info
OS: Fedora 27
fuse-nio-adapter: commit 2073845c37462276b335a6300d946efc706a1d27 

## Description
Accessing a file on Linux results in a I/O-error and throws a `java.io.IOException`, even with the `ReadOnlyAdapter`
howto:
1. start adapter (e.g. mount `~\test` at `~\mnt`)
1. place a textfile into `~\test` (e.g. `asd.txt`)
1. switch with console into `~\mnt`
1. try to output some content of `asd.txt` , e.g. with `cat`

## Attachments (optional)
```
LOOKUP /fuse-nio-adapter.log
getattr /fuse-nio-adapter.log
   NODEID: 7
   unique: 352, success, outsize: 144
unique: 353, opcode: OPENDIR (27), nodeid: 1, insize: 48, pid: 4458
   unique: 353, success, outsize: 32
unique: 354, opcode: GETATTR (3), nodeid: 1, insize: 56, pid: 4458
getattr /
   unique: 354, success, outsize: 120
unique: 355, opcode: READDIR (28), nodeid: 1, insize: 80, pid: 4458
readdir[0] from 0
   unique: 355, success, outsize: 440
unique: 356, opcode: READDIR (28), nodeid: 1, insize: 80, pid: 4458
   unique: 356, success, outsize: 16
unique: 357, opcode: RELEASEDIR (29), nodeid: 1, insize: 64, pid: 0
   unique: 357, success, outsize: 16
unique: 358, opcode: GETATTR (3), nodeid: 1, insize: 56, pid: 3125
getattr /
   unique: 358, success, outsize: 120
unique: 359, opcode: OPEN (14), nodeid: 7, insize: 48, pid: 4459
open flags: 0x8000 /fuse-nio-adapter.log
[Thread-220] ERROR org.cryptomator.frontend.fuse.ReadOnlyFileHandler - Error opening file.
java.io.IOException: Unsupported open flags: __UNKNOWN_CONSTANT__
	at org.cryptomator.frontend.fuse.ReadOnlyFileHandler.open(ReadOnlyFileHandler.java:56)
	at org.cryptomator.frontend.fuse.ReadOnlyFileHandler.open(ReadOnlyFileHandler.java:36)
	at org.cryptomator.frontend.fuse.ReadOnlyAdapter.open(ReadOnlyAdapter.java:126)
	at ru.serce.jnrfuse.AbstractFuseFS.lambda$init$2(AbstractFuseFS.java:131)
	at jnr.ffi.provider.jffi.NativeClosureProxy$$impl$$1.invoke(Unknown Source)
   unique: 359, error: -5 (Eingabe-/Ausgabefehler), outsize: 16
```

**Comment by overheadhunter** [comment]
Maybe we should just ignore unsupported flags instead of complaining (read: throwing exceptions) about them.

**Comment by infeo** [comment]
also think this is the best solution. Log the unknown flag, but proceed with a default readonly case.
But then another error occurs: When accessing the file, the file is shown to be empty, which is not the case. See issue #7
